apiVersion: v1
entries:
  camel-k:
  - apiVersion: v2
    appVersion: 1.3.2-SNAPSHOT
    created: "2021-03-23T14:58:37.720433259+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 30d999fb1a24c741829cd3ad1c1ba3c8ac4d0571a9ad1258c327c426913312d7
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2021-03-23T14:58:37.718860232+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 222b6b51ac7c836e1a7cfe44228de3666cb2b4c559c64bee35afaef9cbfe2449
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2021-03-23T14:58:37.716842491+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 393f4e4b32119824442ee2abdfc34a34bc49ec0fc6e957057e955cb5dd63aece
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2021-03-23T14:58:37.715307621+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: c47863e13644340b857acf5c688004927e0ad126a9c39e8c90fa6d84e2c445b9
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2021-03-23T14:58:37.713432188+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 46771bd1c0e52097f07e9c17e657690872716ed845b196cd0c981c97b984b573
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2021-03-23T14:58:37.712035489+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: d7453b9b6281355caad37896c6760be64735f69009bc312a54cbc17e8a1f6697
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-03-23T14:58:37.711698167+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 610a2b024d539451ee278b72179f34c242a67b7949e2a4eae7b0fa2d8d3630e3
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.0.0-RC2
    created: "2021-03-23T14:58:37.71134284+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 3d5397e111004a8735849dcebd55c9827e687aa3ab28b5c28de8fe69595e1b8f
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.0.0-RC2
    created: "2021-03-23T14:58:37.710945802+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 43fa5d9563ce76d25695e4132c5870279541b26be2ac8023537b587483853260
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.0-RC2
    created: "2021-03-23T14:58:37.710580831+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 3bc8c53c4d781c4b4e4aac254d291339b348c2d8b4cf24b579ceb4330a48edd5
    home: https://camel.apache.org/camel-k/latest/
    icon: https://raw.githubusercontent.com/apache/camel/master/docs/img/logo-d.svg
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.1.0.tgz
    version: 0.1.0
generated: "2021-03-23T14:58:37.710056384+01:00"
