apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: camelcatalogs.camel.apache.org
  labels:
    app: "camel-k"
spec:
  group: camel.apache.org
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  names:
    kind: CamelCatalog
    listKind: CamelCatalogList
    plural: camelcatalogs
    singular: camelcatalog
    shortNames:
    - cc
  additionalPrinterColumns:
    - name: Version
      type: string
      description: The Catalog version
      JSONPath: .spec.version
