apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.camel.apache.org
  labels:
    app: "camel-k"
spec:
  group: camel.apache.org
  scope: Namespaced
  version: v1alpha1
  names:
    kind: Build
    listKind: BuildList
    plural: builds
    singular: build
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Phase
      type: string
      description: The build phase
      JSONPath: .status.phase
    - name: Age
      type: date
      description: The time at which the build was last (re-)started
      JSONPath: .status.startedAt
    - name: Duration
      type: string
      # Change when CRD uses OpenAPI spec v3
      # https://github.com/OAI/OpenAPI-Specification/issues/845
      # format: duration
      description: The build last execution duration
      JSONPath: .status.duration
