--- # ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: Nightly check against ARM64 architecture and JDK21

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  schedule:
    - cron: "10 4 * * *"
  workflow_dispatch:

jobs:
  common-arm64:
    strategy:
      matrix:
        # We want to check this on latest development branch only
        ref-branch: [main]

    if: github.repository == 'apache/camel-k'
    runs-on: ubuntu-24.04-arm
    steps:

    - name: "Checkout code"
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.ref-branch }}
        persist-credentials: false
        submodules: recursive

    - name: Infra setting
      uses: ./.github/actions/infra-setting

    - name: Install operator
      shell: bash
      run: |
        THIS_VERSION="$(make get-version)"
        VERSION="$(make get-version | sed s/-SNAPSHOT//)-nightly"
        sed "s#apache/camel-k:$THIS_VERSION#testcamelk/camel-k:$VERSION#g" install/base/config/manager/operator-deployment.yaml
        kubectl create ns camel-k
        make install-k8s-global
        kubectl wait --for=jsonpath='{.status.phase}'=Ready itp camel-k -n camel-k --timeout=120s

    - name: Run test
      shell: bash
      run: |
        DO_TEST_PREBUILD=false GOTESTFMT="-json 2>&1 | gotestfmt" make test-common

  common-jdk-21:
    strategy:
      matrix:
        # We want to check this on latest development branch only
        ref-branch: [main]

    if: github.repository == 'apache/camel-k'
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout code"
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.ref-branch }}
        persist-credentials: false
        submodules: recursive

    - name: Infra setting
      uses: ./.github/actions/infra-setting

    - name: Install operator
      shell: bash
      run: |
        VERSION="$(make get-version | sed s/-SNAPSHOT//)-nightly-21-jdk"
        CUSTOM_IMAGE=testcamelk/camel-k CUSTOM_VERSION=$VERSION make bundle
        kubectl create ns camel-k
        make install-k8s-global
        kubectl wait --for=jsonpath='{.status.phase}'=Ready itp camel-k -n camel-k --timeout=120s

    - name: Run test
      shell: bash
      run: |
        DO_TEST_PREBUILD=false GOTESTFMT="-json 2>&1 | gotestfmt" make test-common
